version: '3.1'
services:
  chromadb:
    # https://github.com/chroma-core/chroma/blob/main/docker-compose.yml
    image: chromadb/chroma:latest
    hostname: chromadb
    restart: unless-stopped
    # ports:
    #  - "8000:8000/tcp"
    volumes:
      - ./chromadb-data:/chroma/chroma
    environment:
      ANONYMIZED_TELEMETRY: False # disable telemetry metrics
  flask:
    build: ./flask/
    hostname: flask
    volumes:
      - ./images:/images:ro
    ports:
      - "5000:5000/tcp"
    depends_on:
      - chromadb
      - postgresql
  postgresql:
    image: postgres:16
    hostname: postgresql
    restart: unless-stopped
    # ports:
    #   - "5432:5432/tcp"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: chromadb
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:rw
    depends_on:
      - chromadb
  adminer:
    image: adminer:latest
    hostname: adminer
    restart: unless-stopped
    ports:
      - "8080:8080/tcp"
    depends_on:
      - postgresql